build_input_shape:
  -
  - 28
  - 28
  - 1

dtype: float32

layers:

  - class_name: InputLayer
    config:
      batch_shape:
        -
        - 28
        - 28
        - 1
      dtype: float32
      name: input_layer_1
      sparse: no
    module: keras.layers
    registered_name:

  - build_config:
      input_shape:
        -
        - 28
        - 28
        - 1

    class_name: Conv2D

    config:
      activation: relu
      activity_regularizer:
      bias_constraint:
      bias_initializer:
        class_name: Zeros
        config: {}
        module: keras.initializers
        registered_name:
      bias_regularizer:
      data_format: channels_last
      dilation_rate:
        - 1
        - 1
      dtype: float32
      filters: 32
      groups: 1
      kernel_constraint:
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed:
        module: keras.initializers
        registered_name:
      kernel_regularizer:
      kernel_size:
        - 3
        - 3
      name: conv2d_3
      padding: valid
      strides:
        - 1
        - 1
      trainable: yes
      use_bias: yes

    module: keras.layers

    registered_name:

  - build_config:
      input_shape:
        -
        - 26
        - 26
        - 32
    class_name: MaxPooling2D
    config:
      data_format: channels_last
      dtype: float32
      name: max_pooling2d_2
      padding: valid
      pool_size:
        - 2
        - 2
      strides:
        - 2
        - 2
      trainable: yes
    module: keras.layers
    registered_name:

  - build_config:
      input_shape:
        -
        - 13
        - 13
        - 32

    class_name: Conv2D

    config:
      activation: relu
      activity_regularizer:
      bias_constraint:
      bias_initializer:
        class_name: Zeros
        config: {}
        module: keras.initializers
        registered_name:
      bias_regularizer:
      data_format: channels_last
      dilation_rate:
        - 1
        - 1
      dtype: float32
      filters: 64
      groups: 1
      kernel_constraint:
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed:
        module: keras.initializers
        registered_name:
      kernel_regularizer:
      kernel_size:
        - 3
        - 3
      name: conv2d_4
      padding: valid
      strides:
        - 1
        - 1
      trainable: yes
      use_bias: yes

    module: keras.layers

    registered_name:

  - build_config:
      input_shape:
        -
        - 11
        - 11
        - 64
    class_name: MaxPooling2D
    config:
      data_format: channels_last
      dtype: float32
      name: max_pooling2d_3
      padding: valid
      pool_size:
        - 2
        - 2
      strides:
        - 2
        - 2
      trainable: yes
    module: keras.layers
    registered_name:

  - build_config:
      input_shape:
        -
        - 5
        - 5
        - 64

    class_name: Conv2D

    config:
      activation: relu
      activity_regularizer:
      bias_constraint:
      bias_initializer:
        class_name: Zeros
        config: {}
        module: keras.initializers
        registered_name:
      bias_regularizer:
      data_format: channels_last
      dilation_rate:
        - 1
        - 1
      dtype: float32
      filters: 64
      groups: 1
      kernel_constraint:
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed:
        module: keras.initializers
        registered_name:
      kernel_regularizer:
      kernel_size:
        - 3
        - 3
      name: conv2d_5
      padding: valid
      strides:
        - 1
        - 1
      trainable: yes
      use_bias: yes

    module: keras.layers

    registered_name:

  - build_config:
      input_shape:
        -
        - 3
        - 3
        - 64
    class_name: Flatten
    config:
      data_format: channels_last
      dtype: float32
      name: flatten_1
      trainable: yes
    module: keras.layers
    registered_name:

  - build_config:
      input_shape:
        -
        - 576
    class_name: Dense
    config:
      activation: relu
      bias_constraint:
      bias_initializer:
        class_name: Zeros
        config: {}
        module: keras.initializers
        registered_name:
      bias_regularizer:
      dtype: float32
      kernel_constraint:
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed:
        module: keras.initializers
        registered_name:
      kernel_regularizer:
      name: dense_2
      trainable: yes
      units: 64
      use_bias: yes
    module: keras.layers
    registered_name:

  - build_config:
      input_shape:
        -
        - 64
    class_name: Dense
    config:
      activation: softmax
      bias_constraint:
      bias_initializer:
        class_name: Zeros
        config: {}
        module: keras.initializers
        registered_name:
      bias_regularizer:
      dtype: float32
      kernel_constraint:
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed:
        module: keras.initializers
        registered_name:
      kernel_regularizer:
      name: dense_3
      trainable: yes
      units: 10
      use_bias: yes
    module: keras.layers
    registered_name:

name: sequential_1

trainable: yes
